// writes src/Application/UI/trackOutlines.ts: each track's lap as a small svg
// path for the track cards, north up like the minimap (x east, z south).
// rerun when a track changes:
//
//   node scripts/track/outlines.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import '../test/dom-shim.mjs';
import '../test/ts-hooks.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const ring = JSON.parse(
    fs.readFileSync(path.join(root, 'static/models/Tracks/Nordschleife/nordschleife.json'), 'utf8')
);
const { buildDriftParkData } = await import('../../src/Application/Racing/Track/driftPark.ts');

// the long side is this many units, the drawing keeps this much clear round it
const SIZE = 100;
const PAD = 3;
// a corner has to bend the line this far (in units) to be kept
const TOLERANCE = 0.25;

const distanceToSegment = ([px, py], [ax, ay], [bx, by]) => {
    const dx = bx - ax;
    const dy = by - ay;
    const length = dx * dx + dy * dy;
    const t = length ? Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / length)) : 0;
    return Math.hypot(px - (ax + t * dx), py - (ay + t * dy));
};

// ramer-douglas-peucker
const simplify = (points, tolerance) => {
    if (points.length < 3) return points;
    let worst = 0;
    let at = 0;
    for (let i = 1; i < points.length - 1; i++) {
        const d = distanceToSegment(points[i], points[0], points[points.length - 1]);
        if (d > worst) {
            worst = d;
            at = i;
        }
    }
    if (worst <= tolerance) return [points[0], points[points.length - 1]];
    const left = simplify(points.slice(0, at + 1), tolerance);
    return [...left.slice(0, -1), ...simplify(points.slice(at), tolerance)];
};

const round = (value) => Math.round(value * 10) / 10;

const outline = (points) => {
    const flat = points.map(([x, , z]) => [x, z]);
    const xs = flat.map(([x]) => x);
    const zs = flat.map(([, z]) => z);
    const minX = Math.min(...xs);
    const minZ = Math.min(...zs);
    const scale = (SIZE - PAD * 2) / Math.max(Math.max(...xs) - minX, Math.max(...zs) - minZ);
    const drawn = flat.map(([x, z]) => [PAD + (x - minX) * scale, PAD + (z - minZ) * scale]);
    // the loop closes back on the start, so the line is cut there and closed with Z
    const kept = simplify([...drawn, drawn[0]], TOLERANCE).slice(0, -1);
    const width = round((Math.max(...xs) - minX) * scale + PAD * 2);
    const height = round((Math.max(...zs) - minZ) * scale + PAD * 2);
    const path = kept
        .map(([x, y], i) => `${i ? 'L' : 'M'}${round(x)} ${round(y)}`)
        .join('')
        .concat('Z');
    return {
        viewBox: `0 0 ${width} ${height}`,
        path,
        start: [round(drawn[0][0]), round(drawn[0][1])],
        points: kept.length,
    };
};

const tracks = {
    ring: outline(ring.points),
    drift: outline(buildDriftParkData().points),
};
for (const [id, track] of Object.entries(tracks)) {
    console.log(id, track.viewBox, `${track.points} points, ${track.path.length} chars`);
}

const body = Object.entries(tracks)
    .map(
        ([id, { viewBox, path: d, start }]) =>
            `    ${id}: {\n        viewBox: '${viewBox}',\n        start: [${start.join(', ')}],\n        path: '${d}',\n    },`
    )
    .join('\n');
fs.writeFileSync(
    path.join(root, 'src/Application/UI/trackOutlines.ts'),
    `// generated by scripts/track/outlines.mjs from the track data: each lap north\n// up like the minimap, for the track cards. don't edit, rerun it\nexport const TRACK_OUTLINES = {\n${body}\n} as const;\n`
);
