// the draco decoder as real same origin worker files, emitted by webpack in
// dev and production builds. three's DRACOLoader builds the same script into
// a blob worker, which needs worker-src blob: in the page's policy; as its own
// file the worker is just 'self'. the script is three's own: the decoder, then
// the body of DRACOLoader's DRACOWorker function, the way it builds the blob.
//   draco/draco-worker.js     wasm wrapper (the gltf build) + worker
//   draco/draco_decoder.wasm  sent to the workers by the page
//   draco/draco-worker-js.js  asm.js decoder + worker, where csp support
//                             blocks wasm (no 'wasm-unsafe-eval')
const fs = require('fs');
const path = require('path');

const jsm = path.resolve(__dirname, '../node_modules/three/examples/jsm');
const read = (file) => fs.readFileSync(path.join(jsm, file));

const workerBody = () => {
    const source = read('loaders/DRACOLoader.js').toString('utf8');
    const start = source.indexOf('function DRACOWorker()');
    const end = source.indexOf('export {', start);
    if (start < 0 || end < 0) {
        throw new Error('[draco-worker] DRACOWorker not found in three/examples/jsm/loaders/DRACOLoader.js');
    }
    const fn = source.slice(start, end);
    const body = fn.substring(fn.indexOf('{') + 1, fn.lastIndexOf('}'));
    if (!body.includes('DracoDecoderModule') || !body.includes('onmessage')) {
        throw new Error('[draco-worker] DRACOWorker changed shape, check scripts/draco-worker.js');
    }
    return body;
};

module.exports = () => {
    const body = workerBody();
    const worker = (decoder) =>
        Buffer.from(
            [
                '/* generated by scripts/draco-worker.js from three.js DRACOLoader, do not edit */',
                decoder.toString('utf8'),
                '',
                '/* worker */',
                body,
            ].join('\n')
        );
    return {
        'draco/draco-worker.js': worker(read('libs/draco/gltf/draco_wasm_wrapper.js')),
        'draco/draco_decoder.wasm': read('libs/draco/gltf/draco_decoder.wasm'),
        'draco/draco-worker-js.js': worker(read('libs/draco/draco_decoder.js')),
    };
};
